from .admin_views import *
from .brands_views import *
from .category_views import *
from .customer_views import *
from .product_images_views import *
from .product_specs_views import *
from .products_views import *
from .services_views import *
from .shop_views import *
from .staff_views import *
from .orders_views import *