INSERT INTO shop_category (type, name) VALUES
('Pre-built PC', 'Gaming PC'),
('Pre-built PC', 'Home PC'),
('Pre-built PC', 'Office PC'),
('Pre-built PC', 'Workstation PC'),
('Refurbished Products', 'Refurbished Laptops'),
('Refurbished Products', 'Refurbished PC'),
('PC Components', 'Motherboards'),
('PC Components', 'Processors'),
('PC Components', 'Graphics Cards'),
('PC Components', 'Memory'),
('PC Components', 'Storage Drives'),
('PC Components', 'Power Supply Units'),
('PC Components', 'PC Cabinet'),
('PC Components', 'CPU Cooler'),
('PC Components', 'Case Fans'),
('Monitors', 'Gaming Monitors'),
('Monitors', 'Professional Monitors'),
('CCTV Cameras', 'Indoor Cameras'),
('CCTV Cameras', 'Outdoor Cameras'),
('CCTV Cameras', 'CCTV with Audio'),
('CCTV Cameras', '4K Cameras'),
('Peripherals', 'Keyboard'),
('Peripherals', 'Mouse'),
('Peripherals', 'Speakers'),
('Peripherals', 'Headphones'),
('Software', 'Security Software'),
('Software', 'System Software');


INSERT INTO shop_brand(name) VALUES
('Intel'),
('AMD'),
('NVIDIA'),
('ASUS'),
('Dell'),
('LG'),
('MSI'),
('Gigabyte'),
('Corsair'),
('G.Skill'),
('Crucial'),
('Kingston'),
('Seagate'),
('Western Digital'),
('Samsung'),
('Cooler Master'),
('NZXT'),
('Logitech'),
('Razer'),
('SteelSeries'),
('TP-Link'),
('Imou'),
('McAfee'),
('Microsoft');

INSERT INTO shop_specification (category_id, key) VALUES
-- Pre-built PC Specifications
((SELECT id FROM shop_category WHERE name = 'Gaming PC'), 'Processor'),
((SELECT id FROM shop_category WHERE name = 'Gaming PC'), 'RAM Size'),
((SELECT id FROM shop_category WHERE name = 'Gaming PC'), 'Storage Type'),
((SELECT id FROM shop_category WHERE name = 'Gaming PC'), 'Graphics Card Model'),
((SELECT id FROM shop_category WHERE name = 'Gaming PC'), 'Cooling System'),
((SELECT id FROM shop_category WHERE name = 'Home PC'), 'Processor'),
((SELECT id FROM shop_category WHERE name = 'Home PC'), 'RAM Size'),
((SELECT id FROM shop_category WHERE name = 'Office PC'), 'Processor'),
((SELECT id FROM shop_category WHERE name = 'Office PC'), 'RAM Size'),
((SELECT id FROM shop_category WHERE name = 'Workstation PC'), 'Processor'),
((SELECT id FROM shop_category WHERE name = 'Workstation PC'), 'Graphics Card Model'),

-- Refurbished Laptops & PC
((SELECT id FROM shop_category WHERE name = 'Refurbished Laptops'), 'Processor'),
((SELECT id FROM shop_category WHERE name = 'Refurbished Laptops'), 'RAM Size'),
((SELECT id FROM shop_category WHERE name = 'Refurbished Laptops'), 'Storage Type'),
((SELECT id FROM shop_category WHERE name = 'Refurbished Laptops'), 'Screen Size'),
((SELECT id FROM shop_category WHERE name = 'Refurbished PC'), 'Processor'),
((SELECT id FROM shop_category WHERE name = 'Refurbished PC'), 'RAM Size'),

-- PC Components
((SELECT id FROM shop_category WHERE name = 'Motherboards'), 'Chipset'),
((SELECT id FROM shop_category WHERE name = 'Motherboards'), 'Socket Type'),
((SELECT id FROM shop_category WHERE name = 'Motherboards'), 'Memory Slots'),
((SELECT id FROM shop_category WHERE name = 'Processors'), 'Core Count'),
((SELECT id FROM shop_category WHERE name = 'Processors'), 'Threads'),
((SELECT id FROM shop_category WHERE name = 'Processors'), 'Base Clock Speed'),
((SELECT id FROM shop_category WHERE name = 'Processors'), 'Boost Clock Speed'),
((SELECT id FROM shop_category WHERE name = 'Graphics Cards'), 'GPU Model'),
((SELECT id FROM shop_category WHERE name = 'Graphics Cards'), 'Memory Size'),
((SELECT id FROM shop_category WHERE name = 'Graphics Cards'), 'Memory Type'),
((SELECT id FROM shop_category WHERE name = 'Graphics Cards'), 'Core Clock Speed'),
((SELECT id FROM shop_category WHERE name = 'Graphics Cards'), 'TDP'),
((SELECT id FROM shop_category WHERE name = 'Memory'), 'Size'),
((SELECT id FROM shop_category WHERE name = 'Memory'), 'Speed'),
((SELECT id FROM shop_category WHERE name = 'Memory'), 'Type (DDR4/DDR5)'),
((SELECT id FROM shop_category WHERE name = 'Memory'), 'CAS Latency'),
((SELECT id FROM shop_category WHERE name = 'Storage Drives'), 'Type (SSD/HDD)'),
((SELECT id FROM shop_category WHERE name = 'Storage Drives'), 'Capacity'),
((SELECT id FROM shop_category WHERE name = 'Storage Drives'), 'Read Speed'),
((SELECT id FROM shop_category WHERE name = 'Storage Drives'), 'Write Speed'),
((SELECT id FROM shop_category WHERE name = 'Power Supply Units'), 'Wattage'),
((SELECT id FROM shop_category WHERE name = 'Power Supply Units'), 'Efficiency Rating'),
((SELECT id FROM shop_category WHERE name = 'Power Supply Units'), 'Modular Type'),
((SELECT id FROM shop_category WHERE name = 'PC Cabinet'), 'Form Factor'),
((SELECT id FROM shop_category WHERE name = 'PC Cabinet'), 'RGB Lighting'),
((SELECT id FROM shop_category WHERE name = 'PC Cabinet'), 'Cooling Support'),
((SELECT id FROM shop_category WHERE name = 'CPU Cooler'), 'Type (Air/Liquid)'),
((SELECT id FROM shop_category WHERE name = 'CPU Cooler'), 'Fan Speed'),
((SELECT id FROM shop_category WHERE name = 'CPU Cooler'), 'Noise Level'),
((SELECT id FROM shop_category WHERE name = 'Case Fans'), 'Size'),
((SELECT id FROM shop_category WHERE name = 'Case Fans'), 'Speed'),
((SELECT id FROM shop_category WHERE name = 'Case Fans'), 'RGB Lighting'),

-- Monitors
((SELECT id FROM shop_category WHERE name = 'Gaming Monitors'), 'Refresh Rate'),
((SELECT id FROM shop_category WHERE name = 'Gaming Monitors'), 'Response Time'),
((SELECT id FROM shop_category WHERE name = 'Gaming Monitors'), 'Resolution'),
((SELECT id FROM shop_category WHERE name = 'Gaming Monitors'), 'Panel Type'),
((SELECT id FROM shop_category WHERE name = 'Gaming Monitors'), 'HDR Support'),
((SELECT id FROM shop_category WHERE name = 'Professional Monitors'), 'Resolution'),
((SELECT id FROM shop_category WHERE name = 'Professional Monitors'), 'Color Accuracy'),

-- CCTV Cameras
((SELECT id FROM shop_category WHERE name = 'Indoor Cameras'), 'Resolution'),
((SELECT id FROM shop_category WHERE name = 'Indoor Cameras'), 'Field of View'),
((SELECT id FROM shop_category WHERE name = 'Indoor Cameras'), 'Night Vision'),
((SELECT id FROM shop_category WHERE name = 'Indoor Cameras'), 'Audio Recording'),
((SELECT id FROM shop_category WHERE name = 'Outdoor Cameras'), 'Weather Resistance'),
((SELECT id FROM shop_category WHERE name = 'Outdoor Cameras'), 'Resolution'),
((SELECT id FROM shop_category WHERE name = 'Outdoor Cameras'), 'Night Vision Range'),
((SELECT id FROM shop_category WHERE name = 'CCTV with Audio'), 'Audio Support'),
((SELECT id FROM shop_category WHERE name = '4K Cameras'), 'Resolution'),

-- Peripherals
((SELECT id FROM shop_category WHERE name = 'Keyboard'), 'Type (Mechanical/Membrane)'),
((SELECT id FROM shop_category WHERE name = 'Keyboard'), 'Switch Type'),
((SELECT id FROM shop_category WHERE name = 'Keyboard'), 'Backlighting'),
((SELECT id FROM shop_category WHERE name = 'Keyboard'), 'Wired/Wireless'),
((SELECT id FROM shop_category WHERE name = 'Mouse'), 'DPI'),
((SELECT id FROM shop_category WHERE name = 'Mouse'), 'Buttons Count'),
((SELECT id FROM shop_category WHERE name = 'Mouse'), 'Connectivity'),
((SELECT id FROM shop_category WHERE name = 'Speakers'), 'Wattage'),
((SELECT id FROM shop_category WHERE name = 'Speakers'), 'Surround Sound'),
((SELECT id FROM shop_category WHERE name = 'Speakers'), 'Bluetooth Support'),
((SELECT id FROM shop_category WHERE name = 'Headphones'), 'Driver Size'),
((SELECT id FROM shop_category WHERE name = 'Headphones'), 'Microphone Included'),
((SELECT id FROM shop_category WHERE name = 'Headphones'), 'Noise Cancellation'),

-- Software
((SELECT id FROM shop_category WHERE name = 'Security Software'), 'License Duration'),
((SELECT id FROM shop_category WHERE name = 'Security Software'), 'Number of Devices'),
((SELECT id FROM shop_category WHERE name = 'System Software'), 'OS Compatibility'),
((SELECT id FROM shop_category WHERE name = 'System Software'), 'Version'),
((SELECT id FROM shop_category WHERE name = 'System Software'), 'License Type');
