# Generated by Django 5.1.4 on 2025-03-24 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPCBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_pc_builds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PCBuildItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('CPU', 'Processor (CPU)'), ('GPU', 'Graphics Card (GPU)'), ('RAM', 'Memory (RAM)'), ('Storage', 'Storage (SSD/HDD)'), ('Motherboard', 'Motherboard'), ('Power Supply', 'Power Supply Unit (PSU)'), ('Cooling', 'Cooling System'), ('Case', 'PC Case'), ('Monitor', 'Monitor'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse')], max_length=20)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.custompcbuild')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_build_items', to='shop.product')),
            ],
        ),
    ]
