# Generated by Django 5.1.4 on 2025-03-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_custompcbuild_pcbuilditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompcbuild',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out for delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='Order Placed', max_length=50),
        ),
    ]
