# Generated by Django 5.1.4 on 2025-02-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_payment_stripe_id_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out for delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='Order Placed', max_length=50),
        ),
    ]
