# Generated by Django 5.1.4 on 2025-01-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_available_stock_product_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
