# Generated by Django 5.1.4 on 2025-01-26 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_available_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoption',
            old_name='additional_cost',
            new_name='price',
        ),
    ]
