# Generated by Django 5.1.4 on 2025-01-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_additional_cost_productoption_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='option',
            field=models.CharField(choices=[('Size', 'Size'), ('Color', 'Color'), ('Capacity', 'Capacity'), ('Speed', 'Speed'), ('Type', 'Type')], max_length=20),
        ),
    ]
